# Generated by Django 2.1.4 on 2019-01-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_deduction_plan'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deductions',
            field=models.ManyToManyField(blank=True, to='payroll.Deduction'),
        ),
    ]
