# Generated by Django 2.2 on 2019-05-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_timelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
