# Generated by Django 2.2 on 2019-05-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190507_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='timelog',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='time_out',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
