# Generated by Django 2.2 on 2019-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190515_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
