# Generated by Django 2.2 on 2019-05-16 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_timelog_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='time_out',
        ),
    ]
