# Generated by Django 2.1.4 on 2019-01-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocker',
            options={'verbose_name': 'Issues/Blockers (#3)', 'verbose_name_plural': 'Issues/Blockers (#3)'},
        ),
        migrations.AlterModelOptions(
            name='done',
            options={'verbose_name': 'What i have worked on (#1)', 'verbose_name_plural': 'What i have worked on (#1)'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'What i am planning to do (#2)', 'verbose_name_plural': 'What i am planning to do (#2)'},
        ),
    ]
