# Generated by Django 2.1.4 on 2019-01-08 02:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190106_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='standup',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
