# Generated by Django 2.1.4 on 2019-01-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_standup_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocker',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='done',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
