# Generated by Django 2.1.4 on 2019-01-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20190109_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocker',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='done',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=99),
        ),
        migrations.AddField(
            model_name='done',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocker',
            name='standup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.Standup'),
        ),
        migrations.AlterField(
            model_name='done',
            name='standup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.Standup'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='standup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.Standup'),
        ),
    ]
