# Generated by Django 2.1.4 on 2019-01-18 04:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20190114_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standup',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', null=True),
        ),
    ]
