# Generated by Django 2.1.4 on 2019-01-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20190118_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocker',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
