# Generated by Django 2.2.1 on 2019-05-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=0),
        ),
    ]
