# Generated by Django 2.2.1 on 2019-05-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_event_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
