# Generated by Django 2.2.1 on 2019-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_event_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='frequency',
        ),
        migrations.AddField(
            model_name='event',
            name='freq_day',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='freq_hr',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='freq_min',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='freq_mo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='freq_week_idx',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
