# Generated by Django 2.2.1 on 2019-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20190515_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='freq_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='freq_hr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='freq_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='freq_mo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='freq_week_idx',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
