# Generated by Django 2.1.4 on 2019-01-01 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('1', '15K'), ('2', '20K'), ('3', '25K'), ('4', '30K'), ('5', '35K'), ('6', '40K')], default='1', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('er', models.DecimalField(decimal_places=2, default=0.0, max_digits=999, verbose_name='Employer Participation')),
                ('ee', models.DecimalField(decimal_places=2, default=0.0, max_digits=999, verbose_name='Empoyee Participation')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('term', models.CharField(choices=[('1', '6 months'), ('2', '12 months (1yr)'), ('3', '24 months (2yrs)'), ('4', '36 months (3yrs)')], default='1', max_length=2)),
                ('monthly_ammort', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
