# Generated by Django 2.1.4 on 2019-04-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_deduction_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payroll_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
