# Generated by Django 2.1.4 on 2019-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_payroll_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
