# Generated by Django 2.1.4 on 2019-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
