# Generated by Django 2.1.4 on 2019-01-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_project_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
