# Generated by Django 2.1.4 on 2019-01-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20190108_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='burn',
            name='date_billed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
